#!/usr/bin/env bash
set -euo pipefail

# NOTE: Expects to run as deploy in deploy directory (/home/deploy on niss-local)

NAME="$1"
CWD=$(pwd)

fail() {
    cd "$CWD"
    rm -r "to_build/$NAME"
    echo "[upgrade-to] exiting: $1" 1>&2
    exit 1
}

cd "to_build/$NAME" || fail "Version $NAME does not exist"
export MIX_ENV=prod
mix deps.get --only prod || fail "Failed to get deps"
mix deps.compile sentry --force || fail "Failed to force compile sentry"
mix release || fail "Failed to build release"
cd "$CWD"

mv "to_build/$NAME/_build/prod/rel/niss_local/" "releases/$NAME/"
rm -r "to_build/$NAME/"

echo "Successfully build $NAME"
